# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h0QLMEsRXW58GjgXJN6WE4WV47kUxsNK
"""

li = [int(i) for i in input('enter the values:').split()]

li.sort(reverse=True)
print(li)